### ISSUE TITLE
npm ERR! notarget No matching version found for discord.js@^12.0.0-dev

### ISSUE THREAD

**Issue by Cyclypse** [xShadoww/discord-captcha-bot#2]
![image](https://user-images.githubusercontent.com/42508727/60720940-80e4e880-9f56-11e9-967f-90cb3514cb9d.png)

been stuck on this
can anyone help me?

**Comment by xShadoww** [comment]
DM me on Discord, xShadow#0001

**Comment by xShadoww** [comment]
the error should be fixed for future cases, clone the repository again
